<?xml version="1.0" encoding="utf-8"?><Database Name="cms" Class="dbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=ALI-PC\SQL2014;Initial Catalog=cms;Persist Security Info=True;User ID=sa" SettingsObjectName="linq.Properties.Settings" SettingsPropertyName="cmsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tbCustomers" Member="tbCustomers">
    <Type Name="tbCustomer">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TelegramId" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Fname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Lname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="mobile" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>